import Head from "next/head";

import { api } from "@/utils/api";
import HomeContent from "@/components/Home";
import Header from "@/components/Header";

import { authOptions } from "@/server/auth";
import { getServerSession } from "next-auth/next";

export default function HomePage() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  console.log(hello);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Home page
      {/* <HomeContent /> */}
    </>
  );
}
